[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = [
    # Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3
    # See also https://github.com/ivmarkov/embuild/issues/16
    "-C", "default-linker-libraries",

    # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110
    "--cfg", "espidf_time64",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_VERSION = "release/v5.0"
ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"
