[package]
name = "sensilo"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2021"

[dependencies]
anyhow = "1"
esp-idf-hal = { version = "0.40.1" }
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }

[build-dependencies]
embuild = "0.31.0"
